Repository VictoryFairy/VictoryFairy-backend, pull requests merged in 2024-08, with the labels that each got.

#16 경기 일정 스크래핑, 현재 경기 스코어 스크래핑 및 DB 반영, 스케쥴러 설정
  .env-example
  package-lock.json
  package.json
  src/app.module.ts
  src/config/database.config.ts
  src/controllers/game.controller.ts
  src/controllers/parking-info.controller.ts
  src/controllers/registered-game.controller.ts
  src/controllers/stadium.controller.ts
  src/controllers/team.controller.ts
  src/controllers/user.controller.ts
  src/dtos/batch-update-game.dto.ts
  src/entities/game.entity.ts
  src/modules/batch.module.ts
  src/modules/game.module.ts
  src/modules/parking-info.module.ts
  src/modules/registered-game.module.ts
  src/modules/stadium.module.ts
  src/modules/team.module.ts
  src/modules/user.module.ts
  src/seeder.service.ts
  src/seeds/stadium.seed.ts
  src/seeds/team.seed.ts
  src/services/batch.service.ts
  src/services/game.service.ts
  src/services/parking-info.service.ts
  src/services/registered-game.service.ts
  src/services/stadium.service.ts
  src/services/team.service.ts
  src/types/crawling-game.type.ts
  src/util/teamid-mapper.ts
  src/util/time-format.ts
Labels: enhancement

#26 등록 경기 API 추가
  .env-example
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/guard/access-token.guard.ts
  src/auth/guard/refresh-token.guard.ts
  src/controllers/game.controller.ts
  src/controllers/parking-info.controller.ts
  src/controllers/rank.controller.ts
  src/controllers/registered-game.controller.ts
  src/controllers/stadium.controller.ts
  src/controllers/team.controller.ts
  src/dtos/batch-update-game.dto.ts
  src/dtos/registered-game.dto.ts
  src/entities/game.entity.ts
  src/entities/parking-info.entity.ts
  src/entities/registered-game.entity.ts
  src/entities/stadium.entity.ts
  src/entities/team.entity.ts
  src/entities/user.entity.ts
  src/modules/batch.module.ts
  src/modules/registered-game.module.ts
  src/modules/scheduling.module.ts
  src/modules/user.module.ts
  src/seeds/stadium.seed.ts
  src/seeds/team.seed.ts
  src/services/aws-s3.service.ts
  src/services/game.service.ts
  src/services/parking-info.service.ts
  src/services/registered-game.service.ts
  src/services/scheduling.service.ts
  src/services/seeder.service.ts
  src/services/stadium.service.ts
  src/services/team.service.ts
  src/services/user.service.ts
  src/types/crawling-game.type.ts
Labels: enhancement

#28 🚑 EB 액세스 키 이름 바꾸고 적용
  .github/workflows/docker-aws-deploy.yml
Labels: bug

#30 ✨ 팀 관련 API 추가
  src/controllers/team.controller.ts
  src/dtos/team.dto.ts
  src/services/game.service.ts
  src/services/team.service.ts
Labels: enhancement

#32 컨트롤러에서 Dto 변환 수행하도록 수정
  src/controllers/registered-game.controller.ts
  src/dtos/registered-game.dto.ts
  src/entities/game.entity.ts
  src/entities/registered-game.entity.ts
  src/entities/stadium.entity.ts
  src/services/registered-game.service.ts
Labels: enhancement

#33 ✨ 경기장 관련 API 추가
  src/controllers/stadium.controller.ts
  src/controllers/team.controller.ts
  src/dtos/stadium.dto.ts
  src/services/stadium.service.ts
Labels: enhancement

#37 경기 관련 API 작성
  src/controllers/game.controller.ts
  src/controllers/parking-info.controller.ts
  src/controllers/registered-game.controller.ts
  src/controllers/stadium.controller.ts
  src/controllers/team.controller.ts
  src/dtos/game.dto.ts
  src/dtos/registered-game.dto.ts
  src/services/game.service.ts
  src/services/registered-game.service.ts
  src/services/scheduling.service.ts
  src/services/stadium.service.ts
Labels: enhancement

#41 주차장 정보 API 추가
  src/controllers/parking-info.controller.ts
  src/dtos/parking-info.dto.ts
  src/modules/parking-info.module.ts
  src/seeds/parking-info.seed.ts
  src/services/parking-info.service.ts
  src/services/seeder.service.ts
Labels: enhancement

#40 경기 중복 등록 방지
  src/dtos/registered-game.dto.ts
  src/entities/registered-game.entity.ts
  src/filters/typeorm-exception.filter.ts
  src/services/registered-game.service.ts
Labels: bug, enhancement

#46 응원가 API 추가
  src/app.module.ts
  src/controllers/cheering-song.controller.ts
  src/dtos/cheering-song.dto.ts
  src/entities/cheering-song.entity.ts
  src/entities/player.entity.ts
  src/entities/team.entity.ts
  src/modules/cheering-song.module.ts
  src/seeds/cheering-song-converter.ts
  src/seeds/raw-cheering-songs/doosan.player.song.json
  src/seeds/raw-cheering-songs/doosan.team.song.json
  src/seeds/raw-cheering-songs/hanhwa.player.song.json
  src/seeds/raw-cheering-songs/hanhwa.team.song.json
  src/seeds/raw-cheering-songs/kia.player.song.json
  src/seeds/raw-cheering-songs/kia.team.song.json
  src/seeds/raw-cheering-songs/kiwoom.player.song.json
  src/seeds/raw-cheering-songs/kiwoom.team.song.json
  src/seeds/raw-cheering-songs/kt.player.song.json
  src/seeds/raw-cheering-songs/kt.team.song.json
  src/seeds/raw-cheering-songs/lg.player.song.json
  src/seeds/raw-cheering-songs/lg.team.song.json
  src/seeds/raw-cheering-songs/lotte.player.song.json
  src/seeds/raw-cheering-songs/lotte.team.song.json
  src/seeds/raw-cheering-songs/nc.player.song.json
  src/seeds/raw-cheering-songs/nc.team.song.json
  src/seeds/raw-cheering-songs/samsung.player.song.json
  src/seeds/raw-cheering-songs/samsung.team.song.json
  src/seeds/raw-cheering-songs/ssg.player.song.json
  src/seeds/raw-cheering-songs/ssg.team.song.json
  src/seeds/refined-cheering-songs/doosan.player.song.json
  src/seeds/refined-cheering-songs/doosan.team.song.json
  src/seeds/refined-cheering-songs/hanhwa.player.song.json
  src/seeds/refined-cheering-songs/hanhwa.team.song.json
  src/seeds/refined-cheering-songs/kia.player.song.json
  src/seeds/refined-cheering-songs/kia.team.song.json
  src/seeds/refined-cheering-songs/kiwoom.player.song.json
  src/seeds/refined-cheering-songs/kiwoom.team.song.json
  src/seeds/refined-cheering-songs/kt.player.song.json
  src/seeds/refined-cheering-songs/kt.team.song.json
  src/seeds/refined-cheering-songs/lg.player.song.json
  src/seeds/refined-cheering-songs/lg.team.song.json
  src/seeds/refined-cheering-songs/lotte.player.song.json
  src/seeds/refined-cheering-songs/lotte.team.song.json
  src/seeds/refined-cheering-songs/nc.player.song.json
  src/seeds/refined-cheering-songs/nc.team.song.json
  src/seeds/refined-cheering-songs/samsung.player.song.json
  src/seeds/refined-cheering-songs/samsung.team.song.json
  src/seeds/refined-cheering-songs/ssg.player.song.json
  src/seeds/refined-cheering-songs/ssg.team.song.json
  src/seeds/stadium.seed.ts
  src/seeds/team.seed.ts
  src/services/cheering-song.service.ts
  src/services/seeder.service.ts
  src/services/team.service.ts
  src/types/cheering-song-seed.type.ts
  tsconfig.json
Labels: enhancement

#47 🐛 경기 취소 시 스코어 업데이트 중단 로직 추가
  src/services/scheduling.service.ts
Labels: bug

#50 API 문서 상세화
  src/controllers/game.controller.ts
  src/controllers/parking-info.controller.ts
  src/controllers/registered-game.controller.ts
  src/controllers/stadium.controller.ts
  src/controllers/team.controller.ts
  src/dtos/game.dto.ts
  src/dtos/parking-info.dto.ts
  src/dtos/registered-game.dto.ts
  src/dtos/stadium.dto.ts
  src/dtos/team.dto.ts
  src/dtos/user-dto.ts
  src/modules/game.module.ts
  src/modules/parking-info.module.ts
  src/modules/registered-game.module.ts
  src/modules/scheduling.module.ts
  src/modules/stadium.module.ts
  src/modules/team.module.ts
  src/services/stadium.service.ts
  src/services/user.service.ts
Labels: documentation, enhancement

#51 점수 업데이트 시 NaN 값을 무시하도록 수정
  src/services/game.service.ts
Labels: bug, help wanted

#49 매일 경기 업데이트 시 등록 경기의 상태 업데이트 로직 추가
  src/dtos/registered-game.dto.ts
  src/entities/registered-game.entity.ts
  src/modules/registered-game.module.ts
  src/modules/scheduling.module.ts
  src/services/game.service.ts
  src/services/registered-game.service.ts
  src/services/scheduling.service.ts
  src/types/registered-game-status.type.ts
Labels: enhancement, help wanted

#54 🐛 직관 경기 등록 시 오류 수정
  src/dtos/registered-game.dto.ts
  src/entities/registered-game.entity.ts
Labels: bug

#62 🐛 주차장 정보 API에서 경기장 정보가 빠진 것 수정
  src/services/parking-info.service.ts
Labels: bug

#65 응원가 필터링 및 검색, 무한 스크롤 구현
  package.json
  src/controllers/cheering-song.controller.ts
  src/dtos/cheering-song.dto.ts
  src/dtos/cursor-page.dto.ts
  src/entities/cheering-song.entity.ts
  src/modules/cheering-song.module.ts
  src/seeds/cheering-song-converter.ts
  src/seeds/refined-cheering-songs/doosan.player.song.json
  src/seeds/refined-cheering-songs/doosan.team.song.json
  src/seeds/refined-cheering-songs/hanhwa.player.song.json
  src/seeds/refined-cheering-songs/hanhwa.team.song.json
  src/seeds/refined-cheering-songs/kia.player.song.json
  src/seeds/refined-cheering-songs/kia.team.song.json
  src/seeds/refined-cheering-songs/kiwoom.player.song.json
  src/seeds/refined-cheering-songs/kiwoom.team.song.json
  src/seeds/refined-cheering-songs/kt.player.song.json
  src/seeds/refined-cheering-songs/kt.team.song.json
  src/seeds/refined-cheering-songs/lg.player.song.json
  src/seeds/refined-cheering-songs/lg.team.song.json
  src/seeds/refined-cheering-songs/lotte.player.song.json
  src/seeds/refined-cheering-songs/lotte.team.song.json
  src/seeds/refined-cheering-songs/nc.player.song.json
  src/seeds/refined-cheering-songs/nc.team.song.json
  src/seeds/refined-cheering-songs/samsung.player.song.json
  src/seeds/refined-cheering-songs/samsung.team.song.json
  src/seeds/refined-cheering-songs/ssg.player.song.json
  src/seeds/refined-cheering-songs/ssg.team.song.json
  src/services/cheering-song.service.ts
  src/types/seed.type.ts
Labels: enhancement

#67 🐛 등록 경기의 status 변경 및 생성 시 status 반영
  src/services/game.service.ts
  src/services/registered-game.service.ts
  src/types/registered-game-status.type.ts
Labels: bug, enhancement

#68 🩹 등록되어 있지 않은 경기장 필터링
  src/services/stadium.service.ts
Labels: bug, enhancement

#70 ✨ 직관 경기 이미지 등록 및 이미지 삭제 엔드포인트 추가
  src/controllers/aws-s3.controller.ts
  src/dtos/aws-s3.dto.ts
  src/services/aws-s3.service.ts
Labels: enhancement

#72 📝 API 문서에 예시 보강
  src/controllers/cheering-song.controller.ts
  src/controllers/parking-info.controller.ts
  src/controllers/registered-game.controller.ts
  src/controllers/stadium.controller.ts
  src/controllers/team.controller.ts
Labels: documentation, enhancement

#73 Feature/rank
  src/app.module.ts
  src/config/redis.config.ts
  src/controllers/rank.controller.ts
  src/dtos/rank.dto.ts
  src/entities/user.entity.ts
  src/modules/rank.module.ts
  src/modules/redis.module.ts
  src/services/custom-redis.service.ts
  src/services/rank.service.ts
  src/services/registered-game.service.ts
  src/services/seeder.service.ts
  src/services/user.service.ts
Labels: enhancement

#77 🩹 등록 경기 수정 메소드를 Patch로 변경 및 이에 맞게 서비스 로직 수정
  src/controllers/registered-game.controller.ts
  src/services/registered-game.service.ts
Labels: bug, enhancement

#71 응원가 좋아요 기능 추가
  src/controllers/cheering-song.controller.ts
  src/controllers/registered-game.controller.ts
  src/dtos/like.dto.ts
  src/entities/cheering-song.entity.ts
  src/entities/like-cheering-song.entity.ts
  src/entities/user.entity.ts
  src/modules/cheering-song.module.ts
  src/services/cheering-song.service.ts
  src/services/game.service.ts
Labels: enhancement

#82 🩹 DTO 프론트 뷰에 맞게 변경
  src/controllers/cheering-song.controller.ts
  src/dtos/cheering-song.dto.ts
  src/dtos/cursor-page.dto.ts
  src/dtos/game.dto.ts
  src/dtos/player.dto.ts
  src/services/cheering-song.service.ts
  src/services/registered-game.service.ts
Labels: bug, enhancement

#84 ✨ 좋아요한 응원가 목록을 무한 스크롤 정보와 함꼐 반환하는 API 추가
  src/controllers/cheering-song.controller.ts
  src/services/cheering-song.service.ts
Labels: enhancement

#85 사용하지 않는 import 삭제
  src/controllers/cheering-song.controller.ts
  src/dtos/cheering-song.dto.ts
  src/dtos/cursor-page.dto.ts
  src/dtos/registered-game.dto.ts
  src/entities/cheering-song.entity.ts
  src/entities/like-cheering-song.entity.ts
  src/entities/player.entity.ts
  src/services/cheering-song.service.ts
  src/services/game.service.ts
  src/services/registered-game.service.ts
Labels: enhancement

#88 ✨ 좋아요한 응원가 엔드포인트를 타입에 따라 나눔
  src/controllers/cheering-song.controller.ts
  src/services/cheering-song.service.ts
Labels: enhancement

#90 ✏️ 직관 경기 이미지 등록 API 반환 값 구조 변경
  src/controllers/aws-s3.controller.ts
Labels: enhancement

#92 응원가의 유튜브 링크 수정
  src/seeds/convert-invalid-url.ts
  src/seeds/raw-cheering-songs/doosan.player.song.json
  src/seeds/raw-cheering-songs/doosan.team.song.json
  src/seeds/raw-cheering-songs/hanhwa.player.song.json
  src/seeds/raw-cheering-songs/hanhwa.team.song.json
  src/seeds/raw-cheering-songs/kia.player.song.json
  src/seeds/raw-cheering-songs/kia.team.song.json
  src/seeds/raw-cheering-songs/kiwoom.player.song.json
  src/seeds/raw-cheering-songs/kiwoom.team.song.json
  src/seeds/raw-cheering-songs/kt.player.song.json
  src/seeds/raw-cheering-songs/kt.team.song.json
  src/seeds/raw-cheering-songs/lg.player.song.json
  src/seeds/raw-cheering-songs/lg.team.song.json
  src/seeds/raw-cheering-songs/lotte.player.song.json
  src/seeds/raw-cheering-songs/lotte.team.song.json
  src/seeds/raw-cheering-songs/nc.player.song.json
  src/seeds/raw-cheering-songs/nc.team.song.json
  src/seeds/raw-cheering-songs/samsung.player.song.json
  src/seeds/raw-cheering-songs/samsung.team.song.json
  src/seeds/raw-cheering-songs/ssg.player.song.json
  src/seeds/raw-cheering-songs/ssg.team.song.json
  src/seeds/refined-cheering-songs/hanhwa.player.song.json
  src/seeds/refined-cheering-songs/hanhwa.team.song.json
  src/seeds/refined-cheering-songs/kia.player.song.json
  src/seeds/refined-cheering-songs/kia.team.song.json
  src/seeds/refined-cheering-songs/kiwoom.team.song.json
  src/seeds/refined-cheering-songs/kt.team.song.json
  src/seeds/refined-cheering-songs/lotte.player.song.json
  src/seeds/refined-cheering-songs/lotte.team.song.json
  src/seeds/refined-cheering-songs/nc.player.song.json
  src/seeds/refined-cheering-songs/nc.team.song.json
  src/seeds/refined-cheering-songs/samsung.player.song.json
  src/seeds/refined-cheering-songs/samsung.team.song.json
  src/seeds/refined-cheering-songs/ssg.player.song.json
  src/seeds/refined-cheering-songs/ssg.team.song.json
Labels: bug

#93 한 응원가에 대한 좋아요 여부나 좋아요 개수만 반환하는 엔드포인트 삭제
  src/controllers/cheering-song.controller.ts
Labels: bug, enhancement

#94 Feature/rate rank
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/config/redis.config.ts
  src/const/event.const.ts
  src/const/redis.const.ts
  src/controllers/rank.controller.ts
  src/controllers/user.controller.ts
  src/decorator/redis-inject.decorator.ts
  src/dtos/rank.dto.ts
  src/dtos/user.dto.ts
  src/modules/rank.module.ts
  src/modules/redis.module.ts
  src/modules/user.module.ts
  src/services/custom-redis.service.ts
  src/services/rank.service.ts
  src/services/seeder.service.ts
  src/services/user.service.ts
Labels: enhancement

#99 💚 EB 버전 레이블 변경
  .github/workflows/docker-aws-deploy.yml
Labels: bug

#100 🐛 relations를 수정하여 등록 게임의 응답 값에 누락되어 있던 정보 추가
  src/seeds/convert-invalid-url.ts
  src/services/game.service.ts
  src/services/registered-game.service.ts
Labels: bug

#101 🐛 dist에 refined-cheering-songs가 포함되지 않는 현상 수정
  src/seeds/cheering-song.seed.ts
  src/services/cheering-song.service.ts
Labels: bug

#103 버전 라벨 수정 및 relations 겨는 방법 변경
  .github/workflows/docker-aws-deploy.yml
  src/services/game.service.ts
Labels: enhancement

#106 일부 DTO의 키를 스네이크 케이스에서 카멜 케이스로 변경
  src/controllers/cheering-song.controller.ts
  src/dtos/cheering-song.dto.ts
  src/dtos/game.dto.ts
  src/dtos/registered-game.dto.ts
  src/dtos/stadium.dto.ts
Labels: bug, documentation, enhancement

#107 🐛 경기장 DTO 변경하여 fullName 포함하도록 수정
  src/dtos/stadium.dto.ts
Labels: bug

#110 💚 변경된 AWS 설정 반영
  .github/workflows/docker-aws-deploy.yml
Labels: bug

#111 AWS 배포 정상화
  .github/workflows/docker-aws-deploy.yml
  docker-compose.prod.yml
Labels: bug, enhancement

#112 ♻️ 등록 경기의 이미지 주소 값을 nullable 하게 변경
  src/dtos/registered-game.dto.ts
  src/entities/registered-game.entity.ts
  src/services/registered-game.service.ts
Labels: enhancement

#116 ✨ 다음 달 경기의 정보도 가져오도록 수정
  src/dtos/registered-game.dto.ts
  src/services/game.service.ts
  src/services/scheduling.service.ts
  src/utils/get-next-month.util.ts
Labels: enhancement

#121 이미지 삭제 시 그 결과를 로깅
  src/modules/aws-s3.module.ts
  src/modules/registered-game.module.ts
  src/services/aws-s3.service.ts
  src/services/registered-game.service.ts
Labels: enhancement

#123 🐛 innerText가 null 일때 발생하는 오류 수정
  src/services/game.service.ts
Labels: bug

#124 🐛 StatusElement에도 null 체크
  src/services/game.service.ts
Labels: bug

#125 🔊 이미지 업로드 로그 추가 및 이미지 삭제 엔드포인트 제거
  src/controllers/aws-s3.controller.ts
  src/services/aws-s3.service.ts
Labels: enhancement

#127 🔊 이미지 관련 로그 수정
  src/services/aws-s3.service.ts
Labels: bug

#131 🐛 문자 중계의 정보가 잘못되었을 경우의 처리
  src/controllers/game.controller.ts
  src/dtos/batch-update-game.dto.ts
  src/services/game.service.ts
  src/services/scheduling.service.ts
Labels: bug

#132 경기 업데이트 스케쥴러 시간 및 로직 조금 변경
  src/controllers/game.controller.ts
  src/dtos/batch-update-game.dto.ts
  src/services/game.service.ts
  src/services/scheduling.service.ts
Labels: bug

#135 🐛 경기 상태 업데이트 로직 수정
  src/dtos/game.dto.ts
  src/services/aws-s3.service.ts
  src/services/game.service.ts
  src/services/registered-game.service.ts
  src/services/scheduling.service.ts
  src/types/crawling-game.type.ts
Labels: bug

#134 더블 헤더 기능 및 2023, 2024년에 대한 경기 시드 추가 및 최대 병렬 처리 수 설정
  src/seeds/game-months.seed.ts
  src/services/game.service.ts
  src/services/seeder.service.ts
Labels: enhancement

#137 타임존 설정 / 등록 경기의 상태 결정 시 winning_team을 참조하지 않도록 핫픽스
  docker-compose.prod.yml
  docker-compose.yml
  src/services/game.service.ts
  src/services/registered-game.service.ts
Labels: bug

#141 ✏️ defineStatus의 부등호 방향 정상화
  src/services/registered-game.service.ts
Labels: bug

#147 🐛 문자 중계 데이터에서 상태가 null로 들어올 때의 예외 처리
  src/services/game.service.ts
Labels: bug

#148 ♻️ 한달 간 리뷰를 경기 시작일 기준, 최신순으로 정렬
  src/services/registered-game.service.ts
Labels: enhancement

#149 🐛 앱 실행 시batchUpdateGames 크론잡을 삭제해버리는 것 수정
  src/services/scheduling.service.ts
Labels: bug

#150 🐛 유저 삭제 시 My 응원가 cascade 삭제
  src/entities/cheering-song.entity.ts
  src/entities/like-cheering-song.entity.ts
  src/entities/user.entity.ts
Labels: bug

#151 🐛 한 달 동안의 리뷰 반환 로직 select 컬럼 수정
  src/seeds/game-months.seed.ts
  src/services/game.service.ts
  src/services/registered-game.service.ts
Labels: bug

#152 🐛 경기 시간이 변경되었을 경우 고유키 제약조건을 위반하는 것 수정
  src/services/game.service.ts
Labels: bug
